name: Build Flet APK

on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build APK
        run: |
          flet build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-flet-app
          path: build/apk/release/*.apk
          retention-days: 5
